import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { ConversationalSearchServiceClient } from "@google-cloud/discoveryengine";
import dotenv from 'dotenv';

dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();
app.use(express.json());

// --- 1. ENTERPRISE CONFIGURATION ---
// These are hardcoded to ensure the "Finland 404" is bypassed
const PROJECT_ID = "superb-firefly-489705-g3"; 
const LOCATION = "eu"; 
const DATA_STORE_ID = "hessonpajayritysnro1_1773038098495";

// Initialize the Discovery Engine Client pointing to the Global/EU Gateway
const client = new ConversationalSearchServiceClient({
  apiEndpoint: 'eu-discoveryengine.googleapis.com'
});

// --- 2. THE CHAT ENDPOINT ---
app.post('/api/chat', async (req, res) => {
  try {
    const { message } = req.body;

    // Construct the specific path to your "default_config" in the EU
    const servingConfig = `projects/${PROJECT_ID}/locations/${LOCATION}/collections/default_collection/dataStores/${DATA_STORE_ID}/servingConfigs/default_config`;

    const request = {
      servingConfig,
      query: { text: message },
      summarySpec: {
        summaryResultCount: 5,
        includeCitations: true, // Crucial for PDF-based answers
        modelSpec: { 
          version: "stable" 
        },
        // --- 3. TEACHING RULES (System Instructions) ---
        modelPromptSpec: {
          preamble: `
            Olet Hessonpaja-yrityksen asiantuntija-avustaja. 
            SÄÄNNÖT:
            1. Priorisoi AINA vastauksissa Data Storen PDF-tiedostoja (kuten LTS-ohjeita ja Sitran raportteja).
            2. Käytä Google-hakua (Web Search) vain täydentävänä tietona, jos vastausta ei löydy tiedostoistasi.
            3. Jos tiedostoissa ja verkossa on ristiriitaa, luota tiedostoihin.
            4. Vastaa ystävällisesti suomeksi ja viittaa käyttämiisi lähteisiin.
          `
        }
      }
    };

    console.log(`Sending query to Discovery Engine (Region: ${LOCATION})...`);
    
    // Calling the "Converse" method which handles the chat logic
    const [response] = await client.converseConversation(request);
    
    // Extract the summary text generated by the AI
    const replyText = response.reply?.summary?.summaryText || "Pahoittelut, en löytänyt vastausta tiedostoistasi.";
    
    res.json({ text: replyText });

  } catch (error: any) {
    // This will now catch specific Discovery Engine errors (like 403 Permissions)
    console.error("DISCOVERY ENGINE ERROR:", error.message);
    res.status(500).json({ error: error.message });
  }
});

// --- 4. SERVE FRONTEND ---
// This assumes your Vite build output is in the 'dist' folder
app.use(express.static(path.join(__dirname, 'dist')));

app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

// --- 5. START SERVER ---
const PORT = process.env.PORT || 8080;
app.listen(PORT, () => {
  console.log(`🚀 Enterprise Server Live on Port ${PORT}`);
  console.log(`📍 Targeting Data Store: ${DATA_STORE_ID} in ${LOCATION}`);
});
